[project]
name = "raft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "fastapi[standard]>=0.127.0",
    "flask>=3.1.2",
    "uvicorn>=0.40.0",
]
